### ISSUE TITLE
[Feature Request] Response control on API calls

### ISSUE THREAD

**Issue by Deceivious** [geometry-labs/icon-transactions#100]
[Issue Description]
Filtering transaction based on contract address and the method name does not return the call parameters of each of the returned transaction. We are trying to get all the parameters used to call the method. 
It makes sense to trim out less important data points like call parameters. But having to loop through each transaction and calling the transaction details API for each of the transaction hash individually is not efficient.

[Feature Description]
Would it be possible for end users to have some control over what is returned in the response?

Just for example: 
1. Adding a new parameter `?include=call_param` adds call parameters to the response list.
2. Adding a new paramter `?include=response_data` adds response data to the response list
3. Adding a new paramter `?include=call_param,response_data` adds response data and call parameters to the response list

**Comment by pranav925** [comment]
Included the data field to the api list response, feature should be available soon and will be on by default (no extra parameters needed)
