### ISSUE TITLE
internal transaction missing

### ISSUE THREAD

**Issue by pranav925** [geometry-labs/icon-transactions#102]
https://tracker.icon.community/address/hxfc56203484921c3b7a4dee9579d8614d8c8daaf5#internaltransactions
https://tracker.icon.foundation/address/hxfc56203484921c3b7a4dee9579d8614d8c8daaf5#internaltransactions

**Comment by pranav925** [comment]
Transactions service passes this transactions locally. This issue can be resolved with a resync/backfill

**Comment by pranav925** [comment]
Internal transaction exists in block#37,897,465. Not present in kafka, needs to be injected through ETL @shinyfoil

**Comment by shinyfoil** [comment]
37897465 should be fetched now
