### ISSUE TITLE
Slow select by address query

### ISSUE THREAD

**Issue by pranav925** [geometry-labs/icon-transactions#94]
```
2021/11/01 20:24:23 /build/crud/crud_transaction.go:255 SLOW SQL >= 250ms
[42080.194ms[] [rows:25[] 
SELECT
"transactions"."from_address",
"transactions"."to_address",
"transactions"."value",
"transactions"."block_timestamp",
"transactions"."hash",
"transactions"."block_number",
"transactions"."transaction_fee",
"transactions"."receipt_status",
"transactions"."type",
"transactions"."method",
"transactions"."value_decimal" 
FROM "transactions" 
WHERE type = 'transaction' 
AND 
(from_address = 'hx54f7853dc6481b670caf69c5a27c7c8fe5be8269' OR to_address = 'hx54f7853dc6481b670caf69c5a27c7c8fe5be8269') 
ORDER BY block_number desc LIMIT 25
```

**Comment by shinyfoil** [comment]
- Ran the planner on the table as is, and it's coming back as relatively slow (~ 40 seconds, which we knew).
- Tossed the index it's using (transaction_idx_block_number) into the prewarm cache to see if that helped. Didn't do much.
- Ran vacuum on whole transactions db and it seemed mostly clean (I think now that we're not using it for counts, so it's not super full of dead tuples).
- Same deal after vacuum, so I'm not sure where to go now. Maybe we can rebuild the index or something? That seems a bit drastic though.

**Comment by shinyfoil** [comment]
I'm tweaking the performance specs of the volume to see if we can improve things a bit now that we're only using one instance. I'm thinking some things might be getting jammed up while we're doing read/writes.

**Comment by shinyfoil** [comment]
As I'm going through experimenting with things, I'm starting to see that this might be a really bad query to begin with. Even with the index scans, if we're using a completely un-warm instance: it takes >20 mins to plan the query. If we add the index to prewarm, it doesn't get appreciably faster (since I cancelled it before it finished). Now I'm prewarming the whole transactions table and I'm expecting it to be about the 40 seconds we were looking at before.

Are there any other ways we could write this query? @pranav925

**Comment by shinyfoil** [comment]
Did some more experimenting with rewriting the query.

Running the base query without limits changes the plan from a backwards index scan to a heap bitmap scan (which is super fast). The only downside is now we have all the data, which is potentially pretty huge.

Thought maybe I'd be able to trick the planner into letting me return the main filtered data and then run the limit on that, but it was too smart for me.

CTE (no faster):
```
WITH a (from_address, to_address, value, block_timestamp, hash, block_number, transaction_fee, receipt_status, type, method, value_decimal) AS (
    SELECT
        "transactions"."from_address",
        "transactions"."to_address",
        "transactions"."value",
        "transactions"."block_timestamp",
        "transactions"."hash",
        "transactions"."block_number",
        "transactions"."transaction_fee",
        "transactions"."receipt_status",
        "transactions"."type",
        "transactions"."method",
        "transactions"."value_decimal"
    FROM "transactions"
    WHERE type = 'transaction'
    AND (from_address = 'hx54f7853dc6481b670caf69c5a27c7c8fe5be8269' OR to_address = 'hx54f7853dc6481b670caf69c5a27c7c8fe5be8269')
) SELECT * FROM a;
```

Subquery (~3x slower):
```
SELECT *
    FROM (
             SELECT from_address,
                    to_address,
                    value,
                    block_timestamp,
                    hash,
                    block_number,
                    transaction_fee,
                    receipt_status,
                    type,
                    method,
                    value_decimal
             FROM transactions
             WHERE type = 'transaction'
               AND (from_address = 'hx54f7853dc6481b670caf69c5a27c7c8fe5be8269' OR
                    to_address = 'hx54f7853dc6481b670caf69c5a27c7c8fe5be8269')
         ) AS a
ORDER BY a.block_number desc LIMIT 25;
```

Failing us getting this business running faster through various planner tricks, do we have any options for caching?

**Comment by shinyfoil** [comment]
I think I have a resolution that should work. Earlier comment about CTEs wasn't quite accurate for PG >12. Needed to add MATERIALIZED in there, so this works v good.

```
WITH a (from_address, to_address, value, block_timestamp, hash, block_number, transaction_fee, receipt_status, type, method, value_decimal) AS MATERIALIZED (
    SELECT
        "transactions"."from_address",
        "transactions"."to_address",
        "transactions"."value",
        "transactions"."block_timestamp",
        "transactions"."hash",
        "transactions"."block_number",
        "transactions"."transaction_fee",
        "transactions"."receipt_status",
        "transactions"."type",
        "transactions"."method",
        "transactions"."value_decimal"
    FROM "transactions"
    WHERE type = 'transaction'
    AND (from_address = 'cx0000000000000000000000000000000000000001' OR to_address = 'cx0000000000000000000000000000000000000001')
) SELECT * FROM a ORDER BY a.block_number desc LIMIT 25;
```
